name: nspln
type: php
docroot: "public"
php_version: "8.3"
webserver_type: apache-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
use_dns_when_possible: false
composer_version: "2"
web_environment: []
corepack_enable: false
omit_containers: [db]
